"""
Django settings for djangoproj project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")
FRONTEND_BUILD_DIR = os.path.join(FRONTEND_DIR, "build")
FRONTEND_STATIC_DIR = os.path.join(FRONTEND_DIR, "static")
FRONTEND_BUILD_STATIC_DIR = os.path.join(FRONTEND_BUILD_DIR, "static")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.getenv(name)
    if value is None:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


def normalize_allowed_hosts(hosts):
    normalized = []
    for item in hosts:
        candidate = item.strip()
        if not candidate:
            continue

        if candidate == "*":
            normalized.append(candidate)
            continue

        parsed = urlparse(candidate if "://" in candidate else f"//{candidate}")
        host = parsed.hostname or candidate
        if host:
            normalized.append(host)

    return list(dict.fromkeys(normalized))


def normalize_csrf_trusted_origins(origins):
    normalized = []
    for item in origins:
        candidate = item.strip()
        if not candidate:
            continue

        if "://" not in candidate:
            if candidate.startswith("localhost") or candidate.startswith("127.0.0.1"):
                candidate = f"http://{candidate}"
            else:
                candidate = f"https://{candidate}"

        parsed = urlparse(candidate)
        if parsed.scheme and parsed.netloc:
            normalized.append(f"{parsed.scheme}://{parsed.netloc}")

    return list(dict.fromkeys(normalized))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-key-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)
ENVIRONMENT = os.getenv("DJANGO_ENV", "local").strip().lower()
IS_PRODUCTION = ENVIRONMENT in {"prod", "production"}

ALLOWED_HOSTS = normalize_allowed_hosts(
    env_list("DJANGO_ALLOWED_HOSTS", ["localhost", "127.0.0.1"])
)
CSRF_TRUSTED_ORIGINS = normalize_csrf_trusted_origins(
    env_list(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        ["http://localhost:8000", "http://127.0.0.1:8000"],
    )
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
}

# Application definition

INSTALLED_APPS = [
    "djangoapp.apps.DjangoappConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoproj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            FRONTEND_STATIC_DIR,
            FRONTEND_BUILD_DIR,
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoproj.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_USER_MODEL = "djangoapp.User"

JWT_ALGORITHM = os.getenv("DJANGO_JWT_ALGORITHM", "HS256").strip()
JWT_ACCESS_TTL_MINUTES = int(os.getenv("DJANGO_JWT_ACCESS_TTL_MINUTES", "30"))
JWT_REFRESH_TTL_DAYS = int(os.getenv("DJANGO_JWT_REFRESH_TTL_DAYS", "7"))
JWT_SIGNING_KEY = os.getenv("DJANGO_JWT_SECRET_KEY", SECRET_KEY)

JWT_ACCESS_TTL = timedelta(minutes=JWT_ACCESS_TTL_MINUTES)
JWT_REFRESH_TTL = timedelta(days=JWT_REFRESH_TTL_DAYS)

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(STATIC_ROOT, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATICFILES_DIRS = [
    FRONTEND_STATIC_DIR,
    FRONTEND_BUILD_STATIC_DIR,
]

# This section fixes the proxy issue in the browser
# Tells Django the proxy is secure
if env_bool("DJANGO_USE_SECURE_PROXY_SSL_HEADER", default=IS_PRODUCTION):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=IS_PRODUCTION)

# Allows cookies to work across environments.
# Local HTTP: Lax + non-secure for easy login/session.
# Production HTTPS: None + secure for cross-site proxy/front-end usage.
csrf_samesite = os.getenv(
    "DJANGO_CSRF_COOKIE_SAMESITE",
    "None" if IS_PRODUCTION else "Lax",
).strip()
session_samesite = os.getenv(
    "DJANGO_SESSION_COOKIE_SAMESITE",
    "None" if IS_PRODUCTION else "Lax",
).strip()

CSRF_COOKIE_SAMESITE = csrf_samesite
SESSION_COOKIE_SAMESITE = session_samesite

CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=IS_PRODUCTION)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=IS_PRODUCTION)

# Browser rule: SameSite=None cookies must also be Secure.
if CSRF_COOKIE_SAMESITE == "None":
    CSRF_COOKIE_SECURE = True

if SESSION_COOKIE_SAMESITE == "None":
    SESSION_COOKIE_SECURE = True
